version: "2.1"

volumes:
  #  pihole_config:
  # dnsmasq_config:
  # proxy:
  # certs:
  # jellyfin-config:
  # jellyfin-cache:
  # media:
  # jellyfin-lib:
  # calibre:
  # calibre-config:
  portal:
  nextcloud:
  portal-config:
  # proxy_mysql:
  # nextcloud_mysql:
  kolibri:
  kiwix:
  #browser-settings:
  # pulse:
  # map:
  mapeo-libremesh:
  influxdb-data:
  influxdb-config:
  grafana-data:
  grafana-config:
services:
  mapeo-libremesh:
    image: communityfirst/mapeo-bridge:libremesh
    network_mode: host
    volumes:
      - mapeo-libremesh:/root/.mapeo-bridge
 
  kolibri:
    build: services/kolibri
    ports:
      - "8084:8080"
    volumes:
      - kolibri:/root/.kolibri

  kiwix:
    build: services/kiwix
    restart: unless-stopped
    ports:
      - "8085:80"
  #  # Adicionar manual em: resin-data/docker/volumes/<APP ID>_<VOLUME NAME>/_<CONTAINER DIRECTORY>
    volumes:
      - kiwix:/data
    command: "*.zim"
    # Se quiser baixar arquivos
    # uncomment next 2 lines to use it with remote zim file
    # environment:
    #   DOWNLOAD: "https://download.kiwix.org/zim/wikivoyage/wikivoyage_pt_all_maxi_2022-01.zim"
    #   DOWNLOAD: "https://download.kiwix.org/zim/wikipedia/wikipedia_pt_all_maxi_2021-11.zim"
    #   DOWNLOAD: "https://download.kiwix.org/zim/wikisource/wikisource_pt_all_maxi_2022-01.zim"
    #   DOWNLOAD: "https://download.kiwix.org/zim/wiktionary/wiktionary_pt_all_maxi_2022-01.zim"
    #   DOWNLOAD: "https://download.kiwix.org/zim/wikinews/wikinews_pt_all_maxi_2022-01.zim"

   #   DOWNLOAD: "https://download.kiwix.org/zim/wikiversity/wikiversity_pt_all_maxi_2022-01.zim"
  # https://hub.docker.com/_/nextcloud/

  nextcloud:
    image: nextcloud
    privileged: true
    ports:
      - '8087:80'
    volumes:
       - nextcloud:/var/www/html
   #   - nextcloud:/var/www/html/data 
   #     NEXTCLOUD_TRUSTED_DOMAINS: "grauna.local *.balena-devices.com"
    restart: unless-stopped   
  
  
 
  hostname:
    image: balenablocks/hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: grauna
  # https://github.com/balena-io-examples/balena-storage
  external-drive:
    build: services/storage
    privileged: true
    volumes:
      #- media:/usr/src/media
      #- jellyfin-config:/usr/src/jellyfin-config
      - kiwix:/usr/src/kiwix
      # - calibre:/usr/src/calibre
      - portal:/usr/src/portal
      - nextcloud:/usr/src/nextcloud
      - kolibri:/usr/src/kolibri
      # - map:/usr/src/map
  influxdb:
    build: services/influxdb
    privileged: true
    ports:
      - '8086:8086'
      - '25826:25826/udp'
    volumes:
       - influxdb-config:/etc/influxdb/
       - influxdb-data:/var/lib/influxdb
    restart: unless-stopped   
  grafana:
    build: services/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana/
      - grafana-config:/etc/grafana/
    restart: unless-stopped

    


