version: "3"

services:
  web-server:
    image: nginx
    ports:
      - '80:80'
    volumes:
    - './data/web-server/:/usr/share/nginx/html'
    restart: unless-stopped

  kolibri:
    image: treehouses/kolibri
    ports:
      - '8080:8080'
    volumes:
      - './data/kolibri:/root/.kolibri'
    restart: unless-stopped

  kiwix:
    image: kiwix/kiwix-serve
    ports:
      - '8090:80'
    volumes:
      - './data/kiwix/:/data'
    #command: 'wikipedia wikisource wikivoyage wiktionary wikiversity wikibooks'
    restart: unless-stopped

  nextcloud:
    image: nextcloud:21
    ports:
      - '8070:80'
    volumes:
      - './data/next/app/config:/var/www/html/config'
      - './data/next/app/custom_apps:/var/www/html/custom_apps'
      - './data/next/app/data:/var/www/html/data'
      - './data/next/app/themes:/var/www/html/themes'
    restart: unless-stopped

