version: "2.1"

volumes:
  jellyfin-config:
  jellyfin-cache:
  jellyfin-lib:
  media:
  filebrowser-data:
  portal:
  kolibri:
  kiwix:
  browser-settings:
  pulse:
  map:
  mapeo-libremesh:
services:
  # https://hub.docker.com/r/communityfirst/mapeo-bridge
  mapeo-libremesh:
    image: communityfirst/mapeo-bridge:libremesh
    network_mode: host
    volumes:
      - mapeo-libremesh:/root/.mapeo-bridge
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - 8082:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - media:/media
      - jellyfin-lib:/opt/vc/lib
      - 'pulse:/run/pulse'
    environment:
      PUID: 1000
      PGID: 1000
      JELLYFIN_PublishedServerUrl: guarani.io
  # https://hub.docker.com/r/filebrowser/filebrowser
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 8083:80
    volumes:
      - media:/srv
      - 'pulse:/run/pulse'
      - filebrowser-data:/
    environment:
      PGID: 1000
      PUID: 1000
    command: -- c
  kolibri:
    build: services/kolibri
    ports:
      - "8084:8080"
    volumes:
      - kolibri:/root/.kolibri
      - 'pulse:/run/pulse'
  # https://hub.docker.com/r/kiwix/kiwix-serve
  kiwix:
    build: services/kiwix
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - kiwix:/data
      - 'pulse:/run/pulse'
    command: "*.zim"
  # https://hub.docker.com/r/alexta69/metube
  metube:
    image: alexta69/metube
    ports:
      - 8086:8081
    volumes:
      - media:/downloads
      - 'pulse:/run/pulse'
    environment:
      UID: 0
      GID: 0
      DOWNLOAD_DIR: /downloads/metube-video
      AUDIO_DOWNLOAD_DIR: /downloads/metube-audio
  # https://hub.docker.com/r/communityfirst/live-server
  portal:
    build: services/portal
    restart: unless-stopped
    ports:
      - 80:8080
    volumes:
      - portal:/var/www
  map:
    build: services/map
    restart: unless-stopped
    ports:
      - 8090:8080
    volumes:
      - map:/var/www
  # https://github.com/balenablocks/browser
  browser:
    image: balenablocks/browser
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
    volumes:
      - 'browser-settings:/data' # Only required if using PERSISTENT flag (see below)
      - 'pulse:/run/pulse'
    environment:
      PULSE_SERVER: unix:/run/pulse/pulseaudio.socket
      LAUNCH_URL: http://localhost
      PERSISTENT: 1
      SHOW_CURSOR: 1
      DISPLAY_NUM: 1
      KIOSK: 0
  # https://github.com/balenablocks/audio
  audio:
    image: balenablocks/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1  # Only required for bluetooth support
    ports:
      - 4317:4317                 # Only required if using PA over TCP socket
    volumes:
      - 'pulse:/run/pulse'
    environment:
      AUDIO_OUTPUT: AUTO
      AUDIO_VOLUME: 100%
  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: grauna
  # https://github.com/balena-io-examples/balena-storage
  external-drive:
    build: services/storage
    privileged: true
    volumes:
      - media:/usr/src/media
      - jellyfin-config:/usr/src/jellyfin-config
      - kiwix:/usr/src/kiwix
      - portal:/usr/src/portal
      - kolibri:/usr/src/kolibri
      - map:/usr/src/map
      - mapeo-libremesh:/usr/src/mapeo-libremesh