version: "3"

services:
  web-server:
    image: nginx
    ports:
      - '80:80'
    volumes:
    - './data/web-server/:/usr/share/nginx/html'
    restart: unless-stopped

  kolibri:
    image: treehouses/kolibri
    ports:
      - '8080:8080'
    volumes:
      - './data/kolibri:/root/.kolibri'
    restart: unless-stopped

  kiwix:
    image: kiwix/kiwix-serve
    ports:
      - '8090:80'
    volumes:
      - './data/wiki/:/data'
    command: 'wikipedia wikisource wikivoyage wiktionary wikiversity wikibooks'
    restart: unless-stopped

