name: Balena Draft Base23
on:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - 'balena.yml'
      - 'services/**'
    branches:
      - main

jobs:
  balena-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Balena image
        uses: ./.github/actions/deploy-balena-image
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          balena_fleet: "nupef/graunabase23"
          github_ref: ${{ github.ref }}
          github_head_ref: ${{ github.head_ref }}
          balena_draft: true
          release_tag: ${{ github.ref_name }}
          commit: ${{ github.sha }}
